/*
 * Misskey API
 *
 * **Misskey is a decentralized microblogging platform.**   ## Usage **APIはすべてPOSTでリクエスト/レスポンスともにJSON形式です。** 一部のAPIはリクエストに認証情報(APIキー)が必要です。リクエストの際に`i`というパラメータでAPIキーを添付してください。  ### 自分のアカウントのAPIキーを取得する 「設定 > API」で、自分のAPIキーを取得できます。  > アカウントを不正利用される可能性があるため、このトークンは第三者に教えないでください(アプリなどにも入力しないでください)。  ### アプリケーションとしてAPIキーを取得する 直接ユーザーのAPIキーをアプリケーションが扱うのはセキュリティ上のリスクがあるので、 アプリケーションからAPIを利用する際には、アプリケーションとアプリケーションを利用するユーザーが結び付けられた専用のAPIキーを発行します。  #### 1.アプリケーションを登録する まず、あなたのアプリケーションやWebサービス(以後、あなたのアプリと呼びます)をMisskeyに登録します。 [デベロッパーセンター](/dev)にアクセスし、「アプリ > アプリ作成」からアプリを作成してください。  登録が済むとあなたのアプリのシークレットキーが入手できます。このシークレットキーは後で使用します。  > アプリに成りすまされる可能性があるため、極力このシークレットキーは公開しないようにしてください。</p>  #### 2.ユーザーに認証させる アプリを使ってもらうには、ユーザーにアカウントへのアクセスの許可をもらう必要があります。  認証セッションを開始するには、[https://misskey.kurume-nct.com/api/auth/session/generate](#operation/auth/session/generate) へパラメータに`appSecret`としてシークレットキーを含めたリクエストを送信します。 レスポンスとして認証セッションのトークンや認証フォームのURLが取得できるので、認証フォームのURLをブラウザで表示し、ユーザーにフォームを提示してください。  あなたのアプリがコールバックURLを設定している場合、 ユーザーがあなたのアプリの連携を許可すると設定しているコールバックURLに`token`という名前でセッションのトークンが含まれたクエリを付けてリダイレクトします。  あなたのアプリがコールバックURLを設定していない場合、ユーザーがあなたのアプリの連携を許可したことを(何らかの方法で(たとえばボタンを押させるなど))確認出来るようにしてください。  #### 3.アクセストークンを取得する ユーザーが連携を許可したら、[https://misskey.kurume-nct.com/api/auth/session/userkey](#operation/auth/session/userkey) へリクエストを送信します。  上手くいけば、認証したユーザーのアクセストークンがレスポンスとして取得できます。おめでとうございます！  アクセストークンが取得できたら、*「ユーザーのアクセストークン+あなたのアプリのシークレットキーをsha256したもの」*をAPIキーとして、APIにリクエストできます。  APIキーの生成方法を擬似コードで表すと次のようになります: ``` js const i = sha256(userToken + secretKey); ``` 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject83 struct for InlineObject83
type InlineObject83 struct {
	// 名前(ハンドルネームやニックネーム)
	Name *string `json:"name,omitempty"`
	// アカウントの説明や自己紹介
	Description *string `json:"description,omitempty"`
	// 言語
	Lang *string `json:"lang,omitempty"`
	// 住んでいる地域、所在
	Location *string `json:"location,omitempty"`
	// 誕生日 (YYYY-MM-DD形式)
	Birthday *string `json:"birthday,omitempty"`
	// アイコンに設定する画像のドライブファイルID
	AvatarId *string `json:"avatarId,omitempty"`
	// バナーに設定する画像のドライブファイルID
	BannerId *string `json:"bannerId,omitempty"`
	// 壁紙に設定する画像のドライブファイルID
	WallpaperId *string `json:"wallpaperId,omitempty"`
	// 鍵アカウントか否か
	IsLocked bool `json:"isLocked,omitempty"`
	// Botからのフォローを承認制にするか
	CarefulBot bool `json:"carefulBot,omitempty"`
	// フォローしているユーザーからのフォローリクエストを自動承認するか
	AutoAcceptFollowed bool `json:"autoAcceptFollowed,omitempty"`
	// Botか否か
	IsBot bool `json:"isBot,omitempty"`
	// 猫か否か
	IsCat bool `json:"isCat,omitempty"`
	// 投稿の自動ウォッチをするか否か
	AutoWatch bool `json:"autoWatch,omitempty"`
	// アップロードするメディアをデフォルトで「閲覧注意」として設定するか
	AlwaysMarkNsfw bool `json:"alwaysMarkNsfw,omitempty"`
}
